name: Regression run

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Build and test with Maven
        run: mvn clean test